services:
    homebox:
        image: ghcr.io/sysadminsmedia/homebox:latest-rootless
        restart: always
        environment:
            - HBOX_LOG_LEVEL=info
            - HBOX_LOG_FORMAT=json
            - HBOX_WEB_MAX_UPLOAD_SIZE=50 # MB
            - HBOX_OPTIONS_ALLOW_ANALYTICS=true
        env_file:
            - secrets.env
        volumes:
            - /data/homebox/data:/data/
        ports:
            - 7745:7745
